# Lecture 3 - NumPy

## Assignment 1
Assignment 1 will be released later today: it is notebook form. You need to fill in the answers in the cells and produce graphs. It involves markov chains, but everything needed for the assignment is explained in the notebook. It is due on **Friday, October 9th 11:59pm**. If you have any questions, come to the office hours.

Follow the instructions in the notebook and submit in canvas


## NumPy
- Most common package for scientific computing with Python
- Its fundamental object is `np.array`, an multidimensional array of numbers
- Provides linear algebra, Fourier transform, random number capabilities
- Building block for other packages (e.g. SciPy, scikit-learn)
- Open source, huge dev community!

In [65]:
import numpy as np

## Numpy

Main object type is `np.array`

Many ways to create it,

One way is to convert a python list

In [69]:
python_list = [ 1,2,3 ]
np.array(python_list)
print(python_list)
print(type(np.array(python_list)))

[1, 2, 3]
<class 'numpy.ndarray'>


In [70]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

Many times a list comprehension is used to create a list and then converted to a array

In [71]:
arr = np.array([ 2**i for i in [2,3,9] ])
arr

array([  4,   8, 512])

In [72]:
arr = np.array([ 2**i for i in range(10) if i!= 5 ])
arr

array([  1,   2,   4,   8,  16,  64, 128, 256, 512])

### Exercise
Create a numpy array that contain  intergers i  such that  0<i<100 and $2^i$ has the last digit 6

In [77]:
np.array([2**i for i in range(1,100) if (2**i)%10 == 6])

array([16, 256, 4096, 65536, 1048576, 16777216, 268435456, 4294967296,
       68719476736, 1099511627776, 17592186044416, 281474976710656,
       4503599627370496, 72057594037927936, 1152921504606846976,
       18446744073709551616, 295147905179352825856,
       4722366482869645213696, 75557863725914323419136,
       1208925819614629174706176, 19342813113834066795298816,
       309485009821345068724781056, 4951760157141521099596496896,
       79228162514264337593543950336], dtype=object)

Create a 2D numpy array $A$ such that $A_{ij} = i\times j$

In [84]:
n= 10
A = np.array([[i*j for i in range(n)] for j in range(n)])
A[2,3]

6

## Vectorization

In [85]:
def fn(x):
    return x*x + 4*x +5

In [86]:
fn(10)

145

In [87]:
fn(np.linspace(0,1,10))

array([ 5.        ,  5.45679012,  5.9382716 ,  6.44444444,  6.97530864,
        7.5308642 ,  8.11111111,  8.71604938,  9.34567901, 10.        ])

### Exercise
Create an array of first 10 powers of 2

In [90]:
2**np.arange(10)

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

## Another way to create a numpy array is with initializing functions

- np.zeros
- np.ones
- np.arange

These functions along with `reshape` can be used to create initial matrix without any for loops

In [93]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [94]:
5*np.ones((10,10))

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [95]:
np.arange(2,10, 2)

array([2, 4, 6, 8])

You can combine these functions with arithmetic operations

In [96]:
np.zeros((10,10)) + 5

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [97]:
np.ones((10,10))*5

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [103]:
np.arange(10).reshape(10,1)*np.ones((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

### Distinction between numpy 1D arrays and numpy 2D arrays

This tends to cause a lot of confusion for new numpy users.
Follow the below examples carefully to understand the distinction.

In [113]:
X = np.arange(10)
print(X)
print(X.shape)
X[1]

[0 1 2 3 4 5 6 7 8 9]
(10,)


1

In [118]:
Y=np.arange(10).reshape(-1,1)
print(Y)
print(Y.shape)
Y[1,0]

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


1

In [119]:
Z=np.arange(10).reshape(1,-1)
print(Z)
print(Z.shape)
Z[0,1]

[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)


1

In [122]:
W = Z.squeeze()
W[1]

1

In [123]:
Mat = np.random.randn(10,10)

In [132]:
W1 = Mat@Y
W1.shape

(10, 1)

In [137]:
Mat@(Z.transpose()) #Why is .transpose() needed here? What do you think it does?

array([[-8.89433991],
       [ 8.49357996],
       [13.00508218],
       [20.69287126],
       [27.58728943],
       [-6.58485914],
       [-7.15639733],
       [-4.05463243],
       [-1.73875868],
       [ 4.38206535]])

## Array Broadcasting

Normally you only do arithmetic operations between arrays of the same dimension

In [36]:
np.ones((5,5,5)) 

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [140]:
 np.ones((5,5,5)) + np.arange(5*5*5).reshape(5,5,5)

array([[[  1.,   2.,   3.,   4.,   5.],
        [  6.,   7.,   8.,   9.,  10.],
        [ 11.,  12.,  13.,  14.,  15.],
        [ 16.,  17.,  18.,  19.,  20.],
        [ 21.,  22.,  23.,  24.,  25.]],

       [[ 26.,  27.,  28.,  29.,  30.],
        [ 31.,  32.,  33.,  34.,  35.],
        [ 36.,  37.,  38.,  39.,  40.],
        [ 41.,  42.,  43.,  44.,  45.],
        [ 46.,  47.,  48.,  49.,  50.]],

       [[ 51.,  52.,  53.,  54.,  55.],
        [ 56.,  57.,  58.,  59.,  60.],
        [ 61.,  62.,  63.,  64.,  65.],
        [ 66.,  67.,  68.,  69.,  70.],
        [ 71.,  72.,  73.,  74.,  75.]],

       [[ 76.,  77.,  78.,  79.,  80.],
        [ 81.,  82.,  83.,  84.,  85.],
        [ 86.,  87.,  88.,  89.,  90.],
        [ 91.,  92.,  93.,  94.,  95.],
        [ 96.,  97.,  98.,  99., 100.]],

       [[101., 102., 103., 104., 105.],
        [106., 107., 108., 109., 110.],
        [111., 112., 113., 114., 115.],
        [116., 117., 118., 119., 120.],
        [121., 122., 123., 124.,

In [148]:
np.ones((5,5,5)) + np.arange(5).reshape(5,1,1)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]])

In [151]:
np.ones((1,5)) + np.ones((6,1))

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

![](http://scipy-lectures.org/_images/numpy_broadcasting.png)

### Exercise
create a 2D numpy array $A$ such that $A_{ij} = i\times j$, but without using list comprehensions. Use broadcasting instead


In [152]:
np.arange(5).reshape((1,5)) * np.arange(6).reshape((6,1))

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16],
       [ 0,  5, 10, 15, 20]])

Use array broadcasting to create a (10,10) numpy array with values
$$ A_{ij} = 2^i + j $$

In [153]:
2**np.arange(5).reshape((1,5)) + np.arange(6).reshape((6,1))

array([[ 1,  2,  4,  8, 16],
       [ 2,  3,  5,  9, 17],
       [ 3,  4,  6, 10, 18],
       [ 4,  5,  7, 11, 19],
       [ 5,  6,  8, 12, 20],
       [ 6,  7,  9, 13, 21]])

## Matrix creation

There are some functions to create standard matrices

In [155]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [156]:
M = np.diag(np.arange(10))
M

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [157]:
np.diag(M)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
A = np.arange(15).reshape(5,3).T
A

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [166]:
x = np.arange(6).reshape(-1,1)
y = np.arange(5).reshape(1,-1)
np.dot(x,y)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16],
       [ 0,  5, 10, 15, 20]])

In [167]:
x @ y

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16],
       [ 0,  5, 10, 15, 20]])

### Exercise

Create this matrix 
```
array([[5., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 4., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 4., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 5.]])```

In [172]:
np.diag(np.abs(np.arange(11)-5)-1)+1

array([[5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5]])

## Array Indexing and Slicing

In [173]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
arr[5], arr[-2]

(5, 8)

In [184]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [185]:
arr[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [186]:
arr[0:6:2] 

array([0, 2, 4])

In [187]:
arr[5:0:-2]

array([5, 3, 1])

In [191]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [193]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Can use all the above slicing methods for each dimension of a multidemnsional array
![](http://scipy-lectures.org/_images/numpy_indexing.png)

try it yourself

In [194]:
a = 10*np.arange(6).reshape(-1,1)+np.arange(6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [195]:
a[0,3:5]

array([3, 4])

### Exercise
Create the following matrix
```
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])```

In [202]:
a = np.ones((10,10))
a[2:9,2:9] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Create the following matrix
```
array([[-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1.,  0.,  1.,  2.,  3.,  4., -1., -1., -1., -1.],
       [-1.,  5.,  6.,  7.,  8.,  9., -1., -1., -1., -1.],
       [-1., 10., 11., 12., 13., 14., -1., -1., -1., -1.],
       [-1., 15., 16., 17., 18., 19., -1., -1., -1., -1.],
       [-1., 20., 21., 22., 23., 24., -1., -1., -1., -1.],
       [-1., 25., 26., 27., 28., 29., -1., -1., -1., -1.],
       [-1., 30., 31., 32., 33., 34., -1., -1., -1., -1.],
       [-1., 35., 36., 37., 38., 39., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.]])```

# Fancy Array Indexing

We can use numpy arrays as an index for other numpy arrays

In [203]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [213]:
idx = np.array([7,-5,2])
idx

array([ 7, -5,  2])

In [221]:
arr[idx]=-1
arr

array([ 0,  1, -1,  3,  4, -1,  6, -1,  8,  9])

In [222]:
arr<0

array([False, False,  True, False, False,  True, False,  True, False,
       False])

In [224]:
arr[arr<0] = np.arange(3)
arr

array([0, 1, 0, 3, 4, 1, 6, 2, 8, 9])

For multidimensional array, array indexing works different from slicing

In [225]:
X = np.zeros((10,10))
X[3:8,3:9]=1
X

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [227]:
X = np.zeros((10,10))
X[np.arange(3,9),np.arange(3,9)]=1


![](http://scipy-lectures.org/_images/numpy_fancy_indexing.png)

### Exercise
Create the following matrix
```
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])```

### Exercise
Write a function to compute the [trace](https://en.wikipedia.org/wiki/Trace_(linear_algebra)) of a square numpy array using fancy array indexing. Compare your implementation to numpy's built-in function `np.trace`.

In [ ]:
#start here for lecture 4

We can use `np.where`, to get indices of the `True` values in a boolean array

In [ ]:
#X = np.arange(10)
Y = np.zeros((10,10))
Y[np.where(X>0)]=2
Y

## Reduction operations

Many reduction functions are available

- np.sum, np.prod
- np.min, np.max
- np.any, np.all

Partial reductions

- np.cumsum, np.cumprod

In [ ]:
X = np.arange(100).reshape(10,10)
X

In [ ]:
np.sum(X),np.prod(X)

In [ ]:
np.prod(X,axis=1)

In [ ]:
np.min(X),np.max(X)

In [ ]:
np.min(X,axis=0)

In [ ]:
Y = X<1
Y

In [ ]:
np.any(Y)

In [ ]:
np.all(Y)

All the above functions can be called on the array object directly

In [ ]:
X.max(axis=0)

In [ ]:
(np.sqrt(X*X*X)<5000).all()

In [ ]:
np.cumsum(np.ones((10,10)),axis=1)

Cumulative operations don't change the shape of the array

In [ ]:
np.cumsum(X,axis=0)

### Exercise

- Find the column with maximum column sum
- For which rows of the matrix, the sum of the first three elements of the row is greater than the sum of the last two elements of the row

In [ ]:
np.random.seed(10)
X = np.random.rand(5,5)
X

### Exercise
Compute the the moving average of the array `y` created below, with window size 5.

In [ ]:
np.random.seed(10)
y = np.cumsum(np.random.rand(100)-0.5)
import matplotlib.pyplot as plt
plt.plot(y)

In [ ]:
z= np.cumsum(y)
z[5:] = z[5:] - z[:-5] 
z/=5
plt.plot(y)
plt.plot(z)

## Final Exercise

Implement the [Conway's game of Life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life) using numpy

In [ ]:
X = (np.random.rand(100,100)>0.9).astype(int)
import matplotlib.pyplot as plt
plt.imshow(X)

In [ ]:
count =\
X[:-2,:-2] + X[:-2,1:-1] + X[:-2,2::] +\
X[1:-1,:-2] +              X[1:-1,2:] +\
X[2:,:-2] + X[2:,1:-1] +   X[2:,2:]

newX = ((count==3) & (X[1:-1,1:-1]==0)) | (((count==3)|(count==2)) & (X[1:-1,1:-1]==1))
X[:]=0
X[1:-1,1:-1] = newX
plt.imshow(X)